name: Build OASM Nightly

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: oasm/oasm

jobs:

  build:
    name: Build Changed Services
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to image repository
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx with cache support
        run: |
          docker buildx create --name mybuilder --driver docker-container --use
          docker buildx inspect --bootstrap

      - name: Build and push
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            --cache-from=type=registry,ref=${{ env.IMAGE_NAME }}-assistant:buildcache \
            --cache-to=type=registry,ref=${{ env.IMAGE_NAME }}-assistant:buildcache,mode=max \
            --tag ${{ env.IMAGE_NAME }}-assistant:dev \
            --file ./Dockerfile \
            .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME }}-assistant:dev'
          format: 'sarif'
          output: 'trivy-results.assistant.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.assistant.sarif'
